FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:280 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0xc002cf41 0xc010703c 0xc010703c
Translation of call stack:
0xc002cf41: debug_panic (.../../lib/kernel/debug.c:38)
0xc010703c: (unknown)
0xc010703c: (unknown)
